<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CronExpressionDescriptor" Version="2.48.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.11" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jobby.Core\Jobby.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Jobby.Tests.Dashboard" />
    <InternalsVisibleTo Include="Jobby.Tests.Dashboard.Globalization" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" />
  </ItemGroup>

</Project>
